### ISSUE TITLE
Upgrade to v2

### ISSUE THREAD

**Issue by erickwilder** [pennersr/python-bol-api#5]
It's a good time to start thinking on upgrading this to `v2`. Bol.com announced they're going to shutdown `v1` on 01-01-2017.
- Upgrade guide: https://developers.bol.com/documentatie/plaza-api/upgrade-guide-naar-v2/
- Official announcement: https://developers.bol.com/nieuws/plaza-api/nieuws/belangrijk-order-endpoint-plaza-api-eol-01-01-2017/

**Comment by pennersr** [comment]
Work is ongoing in the bol-api-v2 branch...

**Comment by pennersr** [comment]
Branch has been merged into master
